name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

concurrency:
  group: Build ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: monicahq/workflows/.github/workflows/laravel.yml@main
    with:
      php-version: ${{ matrix.php-version }}
      connection: ${{ matrix.connection }}
      coverage: ${{ matrix.connection == 'sqlite' && matrix.php-version == '8.2' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2']
        connection: [sqlite, mysql, pgsql]

  reporting:
    uses: monicahq/workflows/.github/workflows/reporting.yml@main
    with:
      project: monica
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: tests

  assets:
    uses: monicahq/workflows/.github/workflows/build_assets.yml@main
    with:
      node-version: 18
